### ISSUE TITLE
`distinct` method fails to find duplicates in two different `Tiling` instances that are equal

### ISSUE THREAD

**Issue by mcallisto** [scala-tessella/tessella#2]
### Problem

I can have  two `Tiling` instances `t1` and `t2` that are equal

`t1 == t2 && t1.equals(t2) && t1.compare(t2) == 0`

but (unexpectedly, for me) they are not seen as duplicates

`List(t1, t2).distinct == List(t1, t2)`

### Current solution
so I wrote a specialized method where they are seen as duplicates

`Tiling.distinctSafe(List(t1, t2)) == List(t1)`

### Test case

As tested here:

https://github.com/scala-tessella/tessella/blob/1bac18b24181429130fe2ba20a3dbfba647a6ee7/src/test/scala/io/github/scala_tessella/tessella/TilingEqualitySpec.scala#L153-L179

### Questions

My doubts are:

-  is `distinct` working as it should? I guess yes, but why? Is it not relying on `equals` and `compare` to find duplicates?
-  which is the correct approach to reach the results obtained by my `distinctSafe` method?

**Comment by Jasper-M** [comment]
Quoting from the [`equals` scaladoc](https://www.scala-lang.org/api/2.13.10/scala/Any.html#equals(x$1:Any):Boolean) in class `Any`:

> when overriding this method it is usually necessary to override hashCode to ensure that objects which are "equal" (o1.equals(o2) returns true) hash to the same [scala.Int](https://www.scala-lang.org/api/2.13.10/scala/Int.html).

It's an invariant inherited from java [`Object`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Object.html#hashCode()) _if_ `a.equals(b)` _then_ `a.hashCode() == b.hashCode()`.

**Comment by mcallisto** [comment]
@Jasper-M thank you for the explanation, I was under the (wrong and probably hopeful) impression that a `case class` would handle the issue for me...

I will try to implement a dedicated `hashCode()` method. Maybe at that point I can also revert to a standard `class`.

**Comment by Jasper-M** [comment]
`case class` indeed gives you good `equals`, `hashCode` (and `toString`) methods out of the box that give you "value equality" instead of the reference equality that you get by default in normal classes. But if you override those methods you're on your own again unfortunately.

**Comment by mcallisto** [comment]
After further reflection...

I can write `Tiling.code()` function that lists all the elements that would be sequentially compared by `Tiling.equals(...)` to find a difference:  

``` scala
  def code(): List[Int] =
    val start: List[Int] =
      orderedRoundedPerimeterAngles.rotationsAndReflections.min.map(_.toInt).toList ++
       List(graphNodes.size, graphEdges.size, countPolygons)

    @tailrec
    def loop(inner: List[List[PolygonEdges]], acc: List[Int]): List[Int] =
      if inner.isEmpty then
        acc
      else
        val tilings: List[List[PolygonEdges]] =
          inner.flatMap(_.groupConnected(_.hasSharedSidesWith(_)))
        val flattened: List[PolygonEdges] =
          tilings.flatten
        val newAcc: List[Int] =
          flattened.map(_.size).groupBySize.toList.sorted.flatMap(List(_, _)) ++
            List(flattened.flatten.nodes.size, flattened.flatten.size, tilings.size) ++
            acc
        loop(tilings.map(_.strictDeeperPolygons), newAcc)

    loop(List(strictInnerPolygons.toPolygonsEdges.filter(_.nonEmpty)), start)
```

It gives the following results:

``` scala
    tiling1almostEqual.code() shouldBe
      List(9, 20, 12, 3141593, 3141593, 2094395, 2094395, 2094395, 3141593, 3141593, 2094395, 2094395, 2094395, 1, 6, 4, 2, 3, 0, 0, 0)    

    tiling2almostEqual.code() shouldBe
      List(9, 20, 12, 3141593, 3141593, 2094395, 2094395, 2094395, 3141593, 3141593, 2094395, 2094395, 2094395, 1, 6, 4, 2, 3, 0, 0, 0)
```

Now I wonder, what is the correct way to transfom this result into a -possibly unique- `Int`  returned by `hashCode()`?
Considering as I wrote that if the `Tiling` is big the list could contain hundreds or thousands of numbers...

**Comment by Jasper-M** [comment]
> My reasoning is the following: equality between two Tiling instances is defined
> 
> 1. looking first at a some available total data (for example: number of edges and nodes)
> 2. and then checking recursively layer after layer of inner polygons.

Hashcode is not required to be unique for every 2 objects that are not equal. I.e. `a.equals(b) => (a.hashCode == b.hashCode)` but __not__ `a.equals(b) <=> (a.hashCode == b.hashCode)`. So actually `def hashCode() = 0` would be a correct implementation, only performance of any hash based algorithm or data structure would be terrible.

With that in mind, it may be sufficient to calculate a hashCode based only on your first requirement. If you would find that that alone has too many overlapping hashCodes for common cases, you could try to add some more information into the calculation, but still without having to do a fully recursive and complete comparison.

**Comment by mcallisto** [comment]
Really thankful for your help @Jasper-M

I have now, see https://github.com/scala-tessella/tessella/commit/dc782d52f0fa511eb37b2c21d84d424de1e3e7c9:
* overriden `hashCode()` with the fully recursive version based on `private def code`
* deleted my custom `distinctSafe` method

I did not want to prematurely optimize. But, if needed for performance reasons, I could revert to:
* basing `hashCode()` on `private def startingCode`, with only my first requirement
* reintroducing the `distinctSafe` method for safe value equality
